language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - ./gradlew build --scan -s

before_install:
  mvn -pl typescript-generator-core test edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=cz.habarta.typescript.generator.Jackson2ParserTest#testJsonNumberMethodValuedEnum
